import "./globals.css";
import ApiUploadProvider from "@/commons/providers/api-upload-provider"; 
import React from 'react';

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <ApiUploadProvider> 
          {children}
        </ApiUploadProvider>
      </body>
    </html>
  );
}
